#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate all-funds.js from akshare fund data."""
import json
import os
import sys

try:
    import akshare as ak
except ImportError:
    print("akshare not installed. Please run: pip install akshare")
    sys.exit(1)


def map_category(ftype):
    t = str(ftype)
    if '股票型' in t:
        return '股票型'
    if '混合型' in t:
        return '混合型'
    if '债券型' in t:
        return '债券型'
    if '指数型' in t or 'QDII-指数' in t or 'ETF' in t:
        return '指数型'
    if 'QDII' in t:
        return 'QDII'
    if '货币型' in t:
        return '货币型'
    return None


def build_fund_list():
    print("Fetching fund list from akshare...")
    df = ak.fund_name_em()
    print(f"Total funds fetched: {len(df)}")

    seen = set()
    by_cat = {'股票型': [], '混合型': [], '债券型': [], '指数型': [], 'QDII': [], '货币型': []}

    for _, row in df.iterrows():
        code = str(row.iloc[0]).strip()
        name = str(row.iloc[2]).strip()
        ftype = str(row.iloc[3]).strip()
        cat = map_category(ftype)
        if not cat:
            continue
        if code in seen:
            continue
        # Skip C/E/I class shares to reduce duplicates
        if any(name.endswith(s) for s in ['C', 'E', 'I']) and not any(
            name.endswith(s) for s in ['AC', 'BC', 'IC', 'HC', 'LC', 'MC', 'NC', 'OC', 'PC', 'QC', 'RC', 'SC', 'TC', 'UC', 'VC', 'WC', 'XC', 'YC', 'ZC']
        ):
            continue
        seen.add(code)
        by_cat[cat].append({'code': 'of' + code, 'name': name, 'category': cat})

    for cat, lst in by_cat.items():
        print(f"  {cat}: {len(lst)} funds")

    # Sample evenly from each category
    targets = {
        '股票型': 400,
        '混合型': 600,
        '债券型': 400,
        '指数型': 500,
        'QDII': 200,
        '货币型': 200,
    }
    sampled = []
    for cat, target in targets.items():
        lst = by_cat[cat]
        if len(lst) <= target:
            sampled.extend(lst)
        else:
            step = max(1, len(lst) // target)
            sampled.extend(lst[::step][:target])

    # Add ETFs from Sina
    print("Fetching ETF list from Sina...")
    try:
        etfs = ak.fund_etf_category_sina(symbol='ETF基金')
        etf_list = []
        for _, row in etfs.iterrows():
            code = str(row.iloc[0]).strip()
            name = str(row.iloc[1]).strip()
            etf_list.append({'code': code, 'name': name, 'category': '指数型'})
        step = max(1, len(etf_list) // 200)
        sampled_etfs = etf_list[::step][:200]
        sampled.extend(sampled_etfs)
        print(f"  ETFs: {len(sampled_etfs)}")
    except Exception as e:
        print(f"  ETF fetch failed: {e}")

    # Deduplicate by code
    deduped = []
    seen_codes = set()
    for f in sampled:
        if f['code'] not in seen_codes:
            seen_codes.add(f['code'])
            deduped.append(f)

    # Build full list (all non-duplicate funds for search)
    full_list = []
    seen_full = set()
    for cat, lst in by_cat.items():
        for f in lst:
            if f['code'] not in seen_full:
                seen_full.add(f['code'])
                full_list.append(f)
    # Add all ETFs
    try:
        etfs = ak.fund_etf_category_sina(symbol='ETF基金')
        for _, row in etfs.iterrows():
            code = str(row.iloc[0]).strip()
            name = str(row.iloc[1]).strip()
            if code not in seen_full:
                seen_full.add(code)
                full_list.append({'code': code, 'name': name, 'category': '指数型'})
    except Exception:
        pass

    output_dir = os.path.join(os.path.dirname(__file__), '..', 'js')
    os.makedirs(output_dir, exist_ok=True)

    # Write sampled JS file (for default display)
    output_path = os.path.join(output_dir, 'all-funds.js')
    js_content = (
        '// Auto-generated mainstream fund list\n'
        f'// Generated by scripts/build-fund-list.py | Total: {len(deduped)} funds\n\n'
        'const allFunds = ' + json.dumps(deduped, ensure_ascii=False, indent=2) + ';\n'
    )
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(js_content)
    print(f"\nGenerated {output_path}: {len(deduped)} funds ({len(js_content)} bytes)")

    # Write full JS file (for search)
    full_path = os.path.join(output_dir, 'all-funds-full.js')
    full_js = (
        '// Auto-generated full fund list for search\n'
        f'// Generated by scripts/build-fund-list.py | Total: {len(full_list)} funds\n\n'
        'const allFundsFull = ' + json.dumps(full_list, ensure_ascii=False) + ';\n'
    )
    with open(full_path, 'w', encoding='utf-8') as f:
        f.write(full_js)
    print(f"Generated {full_path}: {len(full_list)} funds ({len(full_js)} bytes)")


if __name__ == '__main__':
    build_fund_list()
