#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate all-stocks.js from akshare full A-share list."""
import json
import os
import sys

try:
    import akshare as ak
except ImportError:
    print("akshare not installed. Please run: pip install akshare")
    sys.exit(1)


def build_stock_list():
    print("Fetching A-share stock list from akshare (Sina source)...")
    try:
        df = ak.stock_zh_a_spot()
    except Exception as e:
        print(f"Fetch failed: {e}")
        sys.exit(1)

    print(f"Total stocks fetched: {len(df)}")

    stocks = []
    seen = set()
    for _, row in df.iterrows():
        # Column names may vary; access by position fallback
        code = str(row.iloc[0]).strip()
        name = str(row.iloc[1]).strip()
        if not code or not name:
            continue
        if code in seen:
            continue
        seen.add(code)

        # Determine prefix: sh/sz/bj
        if code.startswith('6'):
            prefix = 'sh'
        elif code.startswith('8') or code.startswith('4'):
            prefix = 'bj'
        else:
            prefix = 'sz'

        stocks.append({
            'rawCode': code,
            'code': prefix + code,
            'name': name
        })

    print(f"Deduplicated: {len(stocks)} stocks")

    # Write JS file
    output_dir = os.path.join(os.path.dirname(__file__), '..', 'js')
    os.makedirs(output_dir, exist_ok=True)
    output_path = os.path.join(output_dir, 'all-stocks.js')

    js_content = (
        '// Auto-generated full A-share stock list\n'
        f'// Generated by scripts/build-stock-list.py | Total: {len(stocks)} stocks\n\n'
        'const allAStockListLocal = ' + json.dumps(stocks, ensure_ascii=False) + ';\n'
    )

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(js_content)

    print(f"\nGenerated {output_path}: {len(stocks)} stocks ({len(js_content)} bytes)")


if __name__ == '__main__':
    build_stock_list()
